# Generated by Django 2.0 on 2018-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
