# Generated by Django 2.0 on 2018-01-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
